import random


def bold():
    CHISTES_CHRIS = [
        "Chris es tan, pero tan pelado, que cuando sale al sol, la NASA lo usa para reflejar señales.",
        "Chris es tan pelado que los insectos lo confunden con una pista de aterrizaje.",
        "Chris es tan pelado que cuando se broncea, solo necesita bloqueador factor espejo.",
        "Chris es tan pelado que en la escuela le decían ‘USB’ porque siempre tenía la cabeza descubierta.",
        "Chris es tan pelado que cuando se disfraza de huevo duro, solo necesita un poco de cáscara.",
        "Chris es tan pelado que cuando llueve, los pájaros se resbalan al intentar posarse en su cabeza.",
        "Chris es tan pelado que su cabeza brilla más que el futuro de Elon Musk.",
        "Chris es tan pelado que cuando se toma una foto, el flash se devuelve solo.",
        "Chris es tan pelado que cuando le preguntan qué shampoo usa, responde ‘Cera para autos’.",
        "Chris es tan pelado que su cabeza tiene menos pelo que una rodilla.",
        "Chris es tan pelado que en los mapas satelitales su cabeza se ve como un segundo sol.",
        "Chris es tan pelado que cuando camina por la calle, lo confunden con una bombilla LED.",
        "Chris es tan pelado que cuando va a la playa, las gaviotas lo siguen pensando que es una boya.",
        "Chris es tan pelado que su frente empieza en la nuca.",
        "Chris es tan pelado que cada vez que se rasca la cabeza, suena como si estuviera limpiando un plato.",
        "Chris es tan pelado que en la fábrica de pelucas lo llaman ‘cliente premium’.",
        "Chris es tan pelado que en Halloween se disfraza de bombillo sin hacer esfuerzo.",
        "Chris es tan pelado que cuando ve una película de terror, el asesino se refleja en su cabeza.",
        "Chris es tan pelado que los médicos lo usan para practicar suturas en superficies lisas.",
        "Chris es tan pelado que cuando se disfraza de genio de la lámpara, solo necesita la lámpara.",
        "Chris es tan pelado que cuando hace calor, su cabeza suda en HD.",
        "Chris es tan pelado que usa crema solar factor aluminio.",
        "Chris es tan pelado que si fuera pirata, no necesitaría catalejo, solo se taparía un ojo con la mano.",
        "Chris es tan pelado que cuando va al zoológico, las tortugas intentan incubar su cabeza.",
        "Chris es tan pelado que si tuviera un euro por cada pelo en la cabeza, tendría deuda.",
        "Chris es tan pelado que si se mete a nadar, los peces piensan que es una boya de seguridad.",
        "Chris es tan pelado que en los aeropuertos lo confunden con un foco de aterrizaje.",
        "Chris es tan pelado que si se pone un tatuaje en la cabeza, parecería una bola mágica 8.",
        "Chris es tan pelado que si se hace un autógrafo en la cabeza, su cuero cabelludo vale más que un NFT.",
        "Chris es tan pelado que la luz de su cuarto solo necesita su reflejo.",
        "Chris es tan pelado que el barbero le cobra el corte como ‘encerado y pulido’.",
        "Chris es tan pelado que en invierno le echa abrillantador en vez de crema humectante.",
        "Chris es tan pelado que las abejas lo persiguen pensando que es un panal gigante.",
        "Chris es tan pelado que cuando le da frío, su cabeza le manda un mensaje de WhatsApp.",
        "Chris es tan pelado que si lo pintan de rojo parece una manzana de feria.",
        "Chris es tan pelado que si entra a un túnel, su cabeza empieza a hacer eco.",
        "Chris es tan pelado que si se cae, su cabeza rebota como pelota de básquet.",
        "Chris es tan pelado que cuando juega al escondite, lo encuentran por el reflejo.",
        "Chris es tan pelado que si fuera un personaje de Mario Kart, su cabeza serviría de caparazón azul.",
        "Chris es tan pelado que en el autocine lo usan para reflejar la película en ultra HD.",
        "Chris es tan pelado que los chicles se deslizan en su cabeza en vez de pegarse.",
        "Chris es tan pelado que cuando le pegan un chicle, sale disparado por falta de fricción.",
        "Chris es tan pelado que cuando era chico, su mamá lo confundía con un huevo de avestruz.",
        "Chris es tan pelado que si lo pintan de amarillo parece un Minion sin gafas.",
        "Chris es tan pelado que si se pone cera en la cabeza, lo pueden usar como lámpara de emergencia.",
        "Chris es tan pelado que si corre bajo el sol, genera suficiente energía para una ciudad pequeña.",
        "Chris es tan pelado que si lo pones en un museo, la gente lo confunde con una escultura renacentista.",
        "Chris es tan pelado que cuando se levanta rápido de la silla, hace ‘plop’ por el vacío que se crea.",
        "Chris es tan pelado que si lo pintas de naranja parece un balón de básquet profesional.",
        "Chris es tan pelado que si se pone una toalla en la cabeza, parece un micrófono de radio.",
        "Chris es tan pelado que si se acerca a un panel solar, empieza a cargarlo solo con la luz reflejada."
    ]

    return random.choice(CHISTES_CHRIS)
